name: CD Pipeline

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  id-token: write
  contents: read
  actions: read

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TF_VAR_subscription_id: ${{secrets.AZURE_SUBSCRIPTION_ID}}
  TF_VAR_foodcore-backend-resource-group: ${{secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME}}
  TF_VAR_foodcore-backend-storage-account: ${{secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME}}
  TF_VAR_foodcore-backend-container: ${{secrets.BACKEND_AZURE_STORAGE_ACCOUNT_CONTAINER_NAME}}
  TF_VAR_foodcore-backend-infra-key: ${{secrets.FOODCORE_INFRA_BACKEND_AZURE_KEY}}
  TF_VAR_swagger_path: "./openapi/openapi.json"

jobs:
  infra-info:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      azfunc_name: ${{ steps.azfunc.outputs.azfunc_name }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        working-directory: terraform
        run: |
          terraform init \
            -backend-config="resource_group_name=${{secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME}}" \
            -backend-config="storage_account_name=${{secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME}}" \
            -backend-config="container_name=${{secrets.BACKEND_AZURE_STORAGE_ACCOUNT_CONTAINER_NAME}}" \
            -backend-config="subscription_id=${{secrets.AZURE_SUBSCRIPTION_ID}}" \
            -backend-config="key=${{secrets.BACKEND_AZURE_KEY}}"

      # Somente para que o output seja criado
      - name: Terraform Apply Refresh Only
        working-directory: terraform
        run: terraform apply --refresh-only --auto-approve

      - name: Get Function App Name from remote state
        id: azfunc
        working-directory: terraform
        run: echo "azfunc_name=$(terraform output -raw azfunc_name_from_remote)" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest
    needs: infra-info

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v11
        with:
          name: functionapp-zip
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ci.yaml
          workflow_search: true
          check_artifacts: true
          name_is_regexp: false
          if_no_artifact_found: fail
          path: azfuncapp
      
      - name: Set Azure Subscription
        run: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Azure Function
        uses: azure/functions-action@v1
        with:
          app-name: ${{ needs.infra-info.outputs.azfunc_name }}
          package: ./azfuncapp/functionapp.zip

  terraform:
    runs-on: ubuntu-latest
    needs: deploy

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="resource_group_name=${{secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME}}" \
            -backend-config="storage_account_name=${{secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME}}" \
            -backend-config="container_name=${{secrets.BACKEND_AZURE_STORAGE_ACCOUNT_CONTAINER_NAME}}" \
            -backend-config="subscription_id=${{secrets.AZURE_SUBSCRIPTION_ID}}" \
            -backend-config="key=${{secrets.BACKEND_AZURE_KEY}}"

      - name: Download artifacts - Tfplan
        uses: dawidd6/action-download-artifact@v11
        with:
          name: tfplan
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ci.yaml
          workflow_search: true
          check_artifacts: true
          name_is_regexp: false
          if_no_artifact_found: fail
          path: terraform
    
      - name: Download artifacts - OpenApi File
        uses: dawidd6/action-download-artifact@v11
        with:
          name: openapi
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ci.yaml
          workflow_search: true
          check_artifacts: true
          name_is_regexp: false
          if_no_artifact_found: fail
          path: terraform/openapi     

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan